name: Build and deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace GIST_KEY
        run: sed -i "s/\${GIST_KEY}/${secrets.GIST_KEY}/g" gist.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .
          github_token: ${{ secrets.GITHUB_TOKEN }}